backend:
  name: github
  repo: Louis-haywood/obtechnical    # your GitHub repo
  branch: main                       # your repo’s main branch

media_folder: "images/uploads"       # where uploaded images go
public_folder: "/images/uploads"     # how they appear on the site

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
